name: TestPlugin
main: io.github.hombrecaca.TestPlugin.TestPlugin
version: 0.1
commands:
   suicidar:
      description: Suicidio.
      usage: /<command> [nombre_jugador]
   soyop:
      description: Consulta si eres OP
      usage: /<command>
   opeame:
      description: Te hace op
      usage: /<command>